-- MySQL Script generated by MySQL Workbench
-- Tue Jan  5 22:51:28 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
        'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gift_certificates_system
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gift_certificates_system
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gift_certificates_system` DEFAULT CHARACTER SET utf8;
USE `gift_certificates_system`;

-- -----------------------------------------------------
-- Table `gift_certificates_system`.`gift_certificate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gift_certificates_system`.`gift_certificate`
(
    `gift_certificate_id`   BIGINT         NOT NULL AUTO_INCREMENT,
    `gift_certificate_name` VARCHAR(100)   NOT NULL,
    `description`           VARCHAR(1000)  NOT NULL,
    `price`                 DECIMAL(10, 2) NOT NULL,
    `duration`              INT            NOT NULL,
    `create_date`           DATETIME       NOT NULL,
    `last_update_date`      DATETIME       NOT NULL,
    PRIMARY KEY (`gift_certificate_id`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gift_certificates_system`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gift_certificates_system`.`tag`
(
    `tag_id`   BIGINT       NOT NULL AUTO_INCREMENT,
    `tag_name` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`tag_id`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gift_certificates_system`.`gift_certificate_has_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gift_certificates_system`.`gift_certificate_has_tag`
(
    `gift_certificate_id_fk` BIGINT NOT NULL,
    `tag_id_fk`              BIGINT NOT NULL,
    PRIMARY KEY (`gift_certificate_id_fk`, `tag_id_fk`),
    INDEX `fk_gift_certificate_has_tag_tag1_idx` (`tag_id_fk` ASC) VISIBLE,
    INDEX `fk_gift_certificate_has_tag_gift_certificate_idx` (`gift_certificate_id_fk` ASC) VISIBLE,
    CONSTRAINT `fk_gift_certificate_has_tag_gift_certificate`
        FOREIGN KEY (`gift_certificate_id_fk`)
            REFERENCES `gift_certificates_system`.`gift_certificate` (`gift_certificate_id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_gift_certificate_has_tag_tag1`
        FOREIGN KEY (`tag_id_fk`)
            REFERENCES `gift_certificates_system`.`tag` (`tag_id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
